-- 03_rg_paises.sql
SET NAMES utf8mb4;

INSERT INTO rg_paises (id,codigo_m49,codigo_iso2,codigo_iso3,nombre,nombre_m49,region_m49,subregion_m49,area_id,tipo_entidad,es_excepcion,nota_asignacion,incluir_mapa,incluir_calculos,tratamiento_fuente,activo) VALUES
(1,'004','AF','AFG','Afghanistan','Afghanistan','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(2,'008','AL','ALB','Albania','Albania','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(3,'012','DZ','DZA','Algeria','Algeria','Africa','Northern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(4,'016','AS','ASM','American Samoa','American Samoa','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(5,'020','AD','AND','Andorra','Andorra','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(6,'024','AO','AGO','Angola','Angola','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(7,'028','AG','ATG','Antigua and Barbuda','Antigua and Barbuda','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(8,'031','AZ','AZE','Azerbaijan','Azerbaijan','Asia','Western Asia',7,'PAIS_SOBERANO',1,'Azerbaiyán se extrae de Asia occidental y se incorpora al Cáucaso postsoviético.','SI','SI','Incluir normalmente.',1),
(9,'032','AR','ARG','Argentina','Argentina','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(10,'036','AU','AUS','Australia','Australia','Oceania','Australia and New Zealand',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(11,'040','AT','AUT','Austria','Austria','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(12,'044','BS','BHS','Bahamas','Bahamas','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(13,'048','BH','BHR','Bahrain','Bahrain','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(14,'050','BD','BGD','Bangladesh','Bangladesh','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(15,'051','AM','ARM','Armenia','Armenia','Asia','Western Asia',7,'PAIS_SOBERANO',1,'Armenia se extrae de Asia occidental y se incorpora al Cáucaso postsoviético.','SI','SI','Incluir normalmente.',1),
(16,'052','BB','BRB','Barbados','Barbados','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(17,'056','BE','BEL','Belgium','Belgium','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(18,'060','BM','BMU','Bermuda','Bermuda','Americas','Northern America',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(19,'064','BT','BTN','Bhutan','Bhutan','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(20,'068','BO','BOL','Bolivia','Bolivia, Plurinational State of','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(21,'070','BA','BIH','Bosnia and Herzegovina','Bosnia and Herzegovina','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(22,'072','BW','BWA','Botswana','Botswana','Africa','Southern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(23,'076','BR','BRA','Brazil','Brazil','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(24,'084','BZ','BLZ','Belize','Belize','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(25,'086','IO','IOT','British Indian Ocean Territory','British Indian Ocean Territory','Africa','Eastern Africa',1,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Se mantiene en maestro y mapa; no se imputa cero.',1),
(26,'090','SB','SLB','Solomon Islands','Solomon Islands','Oceania','Melanesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(27,'092','VG','VGB','Virgin Islands, British','Virgin Islands, British','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(28,'096','BN','BRN','Brunéi','Brunei Darussalam','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(29,'100','BG','BGR','Bulgaria','Bulgaria','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(30,'104','MM','MMR','Myanmar','Myanmar','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(31,'108','BI','BDI','Burundi','Burundi','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(32,'112','BY','BLR','Belarus','Belarus','Europe','Eastern Europe',7,'PAIS_SOBERANO',1,'Bielorrusia se extrae de Europa y se incorpora a Rusia-Eurasia.','SI','SI','Incluir normalmente.',1),
(33,'116','KH','KHM','Cambodia','Cambodia','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(34,'120','CM','CMR','Cameroon','Cameroon','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(35,'124','CA','CAN','Canada','Canada','Americas','Northern America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(36,'132','CV','CPV','Cabo Verde','Cabo Verde','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(37,'136','KY','CYM','Cayman Islands','Cayman Islands','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(38,'140','CF','CAF','Central African Republic','Central African Republic','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(39,'144','LK','LKA','Sri Lanka','Sri Lanka','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(40,'148','TD','TCD','Chad','Chad','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(41,'152','CL','CHL','Chile','Chile','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(42,'156','CN','CHN','China','China','Asia','Eastern Asia',3,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(43,'158','TW','TWN','Taiwan, Province of China','Taiwan, Province of China','Asia','Eastern Asia',2,'ENTIDAD_ESTADISTICA',1,'Taiwán se incorpora estadísticamente a Asia-Pacífico, sin pronunciamiento diplomático.','SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(44,'162','CX','CXR','Christmas Island','Christmas Island','Oceania','Australia and New Zealand',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Sin registro separado comparable para 2025/2050.',1),
(45,'166','CC','CCK','Cocos (Keeling) Islands','Cocos (Keeling) Islands','Oceania','Australia and New Zealand',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Sin registro separado comparable para 2025/2050.',1),
(46,'170','CO','COL','Colombia','Colombia','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(47,'174','KM','COM','Comoros','Comoros','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(48,'175','YT','MYT','Mayotte','Mayotte','Africa','Eastern Africa',1,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(49,'178','CG','COG','Congo','Congo','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(50,'180','CD','COD','Congo, The Democratic Republic of the','Congo, The Democratic Republic of the','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(51,'184','CK','COK','Cook Islands','Cook Islands','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(52,'188','CR','CRI','Costa Rica','Costa Rica','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(53,'191','HR','HRV','Croatia','Croatia','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(54,'192','CU','CUB','Cuba','Cuba','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(55,'196','CY','CYP','Cyprus','Cyprus','Europe','Southern Europe',4,'PAIS_SOBERANO',1,'Chipre se incorpora a Europa como excepción práctica e institucional.','SI','SI','Incluir normalmente.',1),
(56,'203','CZ','CZE','Chequia','Czechia','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(57,'204','BJ','BEN','Benin','Benin','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(58,'208','DK','DNK','Denmark','Denmark','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(59,'212','DM','DMA','Dominica','Dominica','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(60,'214','DO','DOM','Dominican Republic','Dominican Republic','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(61,'218','EC','ECU','Ecuador','Ecuador','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(62,'222','SV','SLV','El Salvador','El Salvador','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(63,'226','GQ','GNQ','Equatorial Guinea','Equatorial Guinea','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(64,'231','ET','ETH','Ethiopia','Ethiopia','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(65,'232','ER','ERI','Eritrea','Eritrea','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(66,'233','EE','EST','Estonia','Estonia','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(67,'234','FO','FRO','Faroe Islands','Faroe Islands','Europe','Northern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(68,'238','FK','FLK','Falkland Islands (Malvinas)','Falkland Islands (Malvinas)','Americas','South America',9,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(69,'242','FJ','FJI','Fiji','Fiji','Oceania','Melanesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(70,'246','FI','FIN','Finland','Finland','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(71,'248','AX','ALA','Åland Islands','Åland Islands','Europe','Northern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Sin registro separado comparable para 2025/2050.',1),
(72,'250','FR','FRA','France','France','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(73,'254','GF','GUF','French Guiana','French Guiana','Americas','South America',9,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(74,'258','PF','PYF','French Polynesia','French Polynesia','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(75,'262','DJ','DJI','Djibouti','Djibouti','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(76,'266','GA','GAB','Gabon','Gabon','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(77,'268','GE','GEO','Georgia','Georgia','Asia','Western Asia',7,'PAIS_SOBERANO',1,'Georgia se extrae de Asia occidental y se incorpora al Cáucaso postsoviético.','SI','SI','Incluir normalmente.',1),
(78,'270','GM','GMB','Gambia','Gambia','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(79,'275','PS','PSE','Palestina','Palestine, State of','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(80,'276','DE','DEU','Germany','Germany','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(81,'288','GH','GHA','Ghana','Ghana','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(82,'292','GI','GIB','Gibraltar','Gibraltar','Europe','Southern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(83,'296','KI','KIR','Kiribati','Kiribati','Oceania','Micronesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(84,'300','GR','GRC','Greece','Greece','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(85,'304','GL','GRL','Greenland','Greenland','Americas','Northern America',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(86,'308','GD','GRD','Grenada','Grenada','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(87,'312','GP','GLP','Guadeloupe','Guadeloupe','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(88,'316','GU','GUM','Guam','Guam','Oceania','Micronesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(89,'320','GT','GTM','Guatemala','Guatemala','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(90,'324','GN','GIN','Guinea','Guinea','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(91,'328','GY','GUY','Guyana','Guyana','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(92,'332','HT','HTI','Haiti','Haiti','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(93,'336','VA','VAT','Holy See (Vatican City State)','Holy See (Vatican City State)','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(94,'340','HN','HND','Honduras','Honduras','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(95,'344','HK','HKG','Hong Kong','Hong Kong','Asia','Eastern Asia',3,'REGION_ESPECIAL',1,'Hong Kong se integra en el área China, manteniendo registro estadístico separado.','SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(96,'348','HU','HUN','Hungary','Hungary','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(97,'352','IS','ISL','Iceland','Iceland','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(98,'356','IN','IND','India','India','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(99,'360','ID','IDN','Indonesia','Indonesia','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(100,'364','IR','IRN','Irán','Iran, Islamic Republic of','Asia','Southern Asia',5,'PAIS_SOBERANO',1,'Irán se traslada de Asia meridional a Oriente Medio por coherencia geopolítica.','SI','SI','Incluir normalmente.',1),
(101,'368','IQ','IRQ','Iraq','Iraq','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(102,'372','IE','IRL','Ireland','Ireland','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(103,'376','IL','ISR','Israel','Israel','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(104,'380','IT','ITA','Italy','Italy','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(105,'384','CI','CIV','Côte d''Ivoire','Côte d''Ivoire','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(106,'388','JM','JAM','Jamaica','Jamaica','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(107,'392','JP','JPN','Japan','Japan','Asia','Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(108,'398','KZ','KAZ','Kazakhstan','Kazakhstan','Asia','Central Asia',7,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(109,'400','JO','JOR','Jordan','Jordan','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(110,'404','KE','KEN','Kenya','Kenya','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(111,'408','KP','PRK','Corea del Norte','Korea, Democratic People''s Republic of','Asia','Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(112,'410','KR','KOR','Corea del Sur','Korea, Republic of','Asia','Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(113,'414','KW','KWT','Kuwait','Kuwait','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(114,'417','KG','KGZ','Kyrgyzstan','Kyrgyzstan','Asia','Central Asia',7,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(115,'418','LA','LAO','Lao People''s Democratic Republic','Lao People''s Democratic Republic','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(116,'422','LB','LBN','Lebanon','Lebanon','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(117,'426','LS','LSO','Lesotho','Lesotho','Africa','Southern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(118,'428','LV','LVA','Latvia','Latvia','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(119,'430','LR','LBR','Liberia','Liberia','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(120,'434','LY','LBY','Libya','Libya','Africa','Northern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(121,'438','LI','LIE','Liechtenstein','Liechtenstein','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(122,'440','LT','LTU','Lithuania','Lithuania','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(123,'442','LU','LUX','Luxembourg','Luxembourg','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(124,'446','MO','MAC','Macao','Macao','Asia','Eastern Asia',3,'REGION_ESPECIAL',1,'Macao se integra en el área China, manteniendo registro estadístico separado.','SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(125,'450','MG','MDG','Madagascar','Madagascar','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(126,'454','MW','MWI','Malawi','Malawi','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(127,'458','MY','MYS','Malaysia','Malaysia','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(128,'462','MV','MDV','Maldives','Maldives','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(129,'466','ML','MLI','Mali','Mali','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(130,'470','MT','MLT','Malta','Malta','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(131,'474','MQ','MTQ','Martinique','Martinique','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(132,'478','MR','MRT','Mauritania','Mauritania','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(133,'480','MU','MUS','Mauritius','Mauritius','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(134,'484','MX','MEX','Mexico','Mexico','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(135,'492','MC','MCO','Monaco','Monaco','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(136,'496','MN','MNG','Mongolia','Mongolia','Asia','Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(137,'498','MD','MDA','Moldavia','Moldova, Republic of','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(138,'499','ME','MNE','Montenegro','Montenegro','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(139,'500','MS','MSR','Montserrat','Montserrat','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(140,'504','MA','MAR','Morocco','Morocco','Africa','Northern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(141,'508','MZ','MOZ','Mozambique','Mozambique','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(142,'512','OM','OMN','Oman','Oman','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(143,'516',NULL,'NAM','Namibia','Namibia','Africa','Southern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(144,'520','NR','NRU','Nauru','Nauru','Oceania','Micronesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(145,'524','NP','NPL','Nepal','Nepal','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(146,'528','NL','NLD','Netherlands','Netherlands','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(147,'531','CW','CUW','Curaçao','Curaçao','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(148,'533','AW','ABW','Aruba','Aruba','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(149,'534','SX','SXM','Sint Maarten (Dutch part)','Sint Maarten (Dutch part)','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(150,'535','BQ','BES','Bonaire, Sint Eustatius and Saba','Bonaire, Sint Eustatius and Saba','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(151,'540','NC','NCL','New Caledonia','New Caledonia','Oceania','Melanesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(152,'548','VU','VUT','Vanuatu','Vanuatu','Oceania','Melanesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(153,'554','NZ','NZL','New Zealand','New Zealand','Oceania','Australia and New Zealand',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(154,'558','NI','NIC','Nicaragua','Nicaragua','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(155,'562','NE','NER','Niger','Niger','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(156,'566','NG','NGA','Nigeria','Nigeria','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(157,'570','NU','NIU','Niue','Niue','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(158,'574','NF','NFK','Norfolk Island','Norfolk Island','Oceania','Australia and New Zealand',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Se excluye superficie para evitar riesgo de doble conteo.',1),
(159,'578','NO','NOR','Norway','Norway','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(160,'580','MP','MNP','Northern Mariana Islands','Northern Mariana Islands','Oceania','Micronesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(161,'583','FM','FSM','Micronesia, Federated States of','Micronesia, Federated States of','Oceania','Micronesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(162,'584','MH','MHL','Marshall Islands','Marshall Islands','Oceania','Micronesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(163,'585','PW','PLW','Palau','Palau','Oceania','Micronesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(164,'586','PK','PAK','Pakistan','Pakistan','Asia','Southern Asia',8,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(165,'591','PA','PAN','Panama','Panama','Americas','Central America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(166,'598','PG','PNG','Papua New Guinea','Papua New Guinea','Oceania','Melanesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(167,'600','PY','PRY','Paraguay','Paraguay','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(168,'604','PE','PER','Peru','Peru','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(169,'608','PH','PHL','Philippines','Philippines','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(170,'612','PN','PCN','Pitcairn','Pitcairn','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Se excluye superficie para consistencia de tratamiento.',1),
(171,'616','PL','POL','Poland','Poland','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(172,'620','PT','PRT','Portugal','Portugal','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(173,'624','GW','GNB','Guinea-Bissau','Guinea-Bissau','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(174,'626','TL','TLS','Timor Oriental','Timor-Leste','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(175,'630','PR','PRI','Puerto Rico','Puerto Rico','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(176,'634','QA','QAT','Qatar','Qatar','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(177,'638','RE','REU','Réunion','Réunion','Africa','Eastern Africa',1,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(178,'642','RO','ROU','Romania','Romania','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(179,'643','RU','RUS','Rusia','Russian Federation','Europe','Eastern Europe',7,'PAIS_SOBERANO',1,'Rusia se extrae de Europa y forma el núcleo de Rusia-Eurasia.','SI','SI','Incluir normalmente.',1),
(180,'646','RW','RWA','Rwanda','Rwanda','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(181,'652','BL','BLM','Saint Barthélemy','Saint Barthélemy','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(182,'654','SH','SHN','Saint Helena, Ascension and Tristan da Cunha','Saint Helena, Ascension and Tristan da Cunha','Africa','Western Africa',1,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(183,'659','KN','KNA','Saint Kitts and Nevis','Saint Kitts and Nevis','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(184,'660','AI','AIA','Anguilla','Anguilla','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(185,'662','LC','LCA','Saint Lucia','Saint Lucia','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(186,'663','MF','MAF','Saint Martin (French part)','Saint Martin (French part)','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(187,'666','PM','SPM','Saint Pierre and Miquelon','Saint Pierre and Miquelon','Americas','Northern America',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(188,'670','VC','VCT','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(189,'674','SM','SMR','San Marino','San Marino','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(190,'678','ST','STP','Sao Tome and Principe','Sao Tome and Principe','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(191,'682','SA','SAU','Saudi Arabia','Saudi Arabia','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(192,'686','SN','SEN','Senegal','Senegal','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(193,'688','RS','SRB','Serbia','Serbia','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(194,'690','SC','SYC','Seychelles','Seychelles','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(195,'694','SL','SLE','Sierra Leone','Sierra Leone','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(196,'702','SG','SGP','Singapore','Singapore','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(197,'703','SK','SVK','Slovakia','Slovakia','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(198,'704','VN','VNM','Vietnam','Viet Nam','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(199,'705','SI','SVN','Slovenia','Slovenia','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(200,'706','SO','SOM','Somalia','Somalia','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(201,'710','ZA','ZAF','South Africa','South Africa','Africa','Southern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(202,'716','ZW','ZWE','Zimbabwe','Zimbabwe','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(203,'724','ES','ESP','Spain','Spain','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(204,'728','SS','SSD','South Sudan','South Sudan','Africa','Middle Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(205,'729','SD','SDN','Sudan','Sudan','Africa','Northern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(206,'732','EH','ESH','Western Sahara','Western Sahara','Africa','Northern Africa',1,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(207,'740','SR','SUR','Suriname','Suriname','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(208,'744','SJ','SJM','Svalbard and Jan Mayen','Svalbard and Jan Mayen','Europe','Northern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=EXCLUIR_INDICADOR; nota=Sin separacion comparable en la fuente principal.',1),
(209,'748','SZ','SWZ','Esuatini','Eswatini','Africa','Southern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(210,'752','SE','SWE','Sweden','Sweden','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(211,'756','CH','CHE','Switzerland','Switzerland','Europe','Western Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(212,'760','SY','SYR','Siria','Syrian Arab Republic','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(213,'762','TJ','TJK','Tajikistan','Tajikistan','Asia','Central Asia',7,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(214,'764','TH','THA','Thailand','Thailand','Asia','South-Eastern Asia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(215,'768','TG','TGO','Togo','Togo','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(216,'772','TK','TKL','Tokelau','Tokelau','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(217,'776','TO','TON','Tonga','Tonga','Oceania','Polynesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(218,'780','TT','TTO','Trinidad and Tobago','Trinidad and Tobago','Americas','Caribbean',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(219,'784','AE','ARE','United Arab Emirates','United Arab Emirates','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(220,'788','TN','TUN','Tunisia','Tunisia','Africa','Northern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(221,'792','TR','TUR','Turquía','Türkiye','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(222,'795','TM','TKM','Turkmenistan','Turkmenistan','Asia','Central Asia',7,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(223,'796','TC','TCA','Turks and Caicos Islands','Turks and Caicos Islands','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(224,'798','TV','TUV','Tuvalu','Tuvalu','Oceania','Polynesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(225,'800','UG','UGA','Uganda','Uganda','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(226,'804','UA','UKR','Ukraine','Ukraine','Europe','Eastern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(227,'807','MK','MKD','North Macedonia','North Macedonia','Europe','Southern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(228,'818','EG','EGY','Egypt','Egypt','Africa','Northern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(229,'826','GB','GBR','Reino Unido','United Kingdom','Europe','Northern Europe',4,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(230,'831','GG','GGY','Guernsey','Guernsey','Europe','Northern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=INCLUIR_POB_EXCLUIR_SUP; nota=No se imputa superficie alternativa sin comparabilidad metodologica cerrada.',1),
(231,'832','JE','JEY','Jersey','Jersey','Europe','Northern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad. | 1C.2A=INCLUIR_POB_EXCLUIR_SUP; nota=No se imputa superficie alternativa sin comparabilidad metodologica cerrada.',1),
(232,'833','IM','IMN','Isle of Man','Isle of Man','Europe','Northern Europe',4,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(233,'834','TZ','TZA','Tanzania','Tanzania, United Republic of','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(234,'840','US','USA','Estados Unidos','United States','Americas','Northern America',6,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(235,'850','VI','VIR','Virgin Islands, U.S.','Virgin Islands, U.S.','Americas','Caribbean',6,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(236,'854','BF','BFA','Burkina Faso','Burkina Faso','Africa','Western Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(237,'858','UY','URY','Uruguay','Uruguay','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(238,'860','UZ','UZB','Uzbekistan','Uzbekistan','Asia','Central Asia',7,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(239,'862','VE','VEN','Venezuela','Venezuela, Bolivarian Republic of','Americas','South America',9,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(240,'876','WF','WLF','Wallis and Futuna','Wallis and Futuna','Oceania','Polynesia',2,'TERRITORIO_DEPENDIENTE',0,NULL,'SI','SEGUN_FUENTE','Comprobar si la fuente lo publica separado y evitar duplicidad.',1),
(241,'882','WS','WSM','Samoa','Samoa','Oceania','Polynesia',2,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(242,'887','YE','YEM','Yemen','Yemen','Asia','Western Asia',5,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(243,'894','ZM','ZMB','Zambia','Zambia','Africa','Eastern Africa',1,'PAIS_SOBERANO',0,NULL,'SI','SI','Incluir normalmente.',1),
(244,NULL,'XK','XKX','Kosovo','Kosovo (auxiliary statistical entity)','Europe','Southern Europe',4,'ENTIDAD_ESTADISTICA',1,'Entidad auxiliar no incluida como entrada principal M49; se usa solo si la fuente aporta datos separados.','SI','SEGUN_FUENTE','No duplicar con Serbia; usar solo cuando la fuente aporte dato separado. | 1C.2A=EXCLUIR_INDICADOR; nota=Se mantiene SEGUN_FUENTE; excluido temporalmente del agregado hasta resolver sin duplicidad.',1);