-- 25_rg_comprobaciones_tecnologia.sql
SET NAMES utf8mb4;
SELECT CASE WHEN COUNT(*)=8 THEN 'OK' ELSE 'NO_OK' END AS bloques_esperados_8 FROM rg_bloques WHERE activo=1;
SELECT CASE WHEN COUNT(*)=27 THEN 'OK' ELSE 'NO_OK' END AS indicadores_esperados_27 FROM rg_indicadores WHERE activo=1;
SELECT CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'NO_OK' END AS bloque_tec_activo FROM rg_bloques WHERE codigo='TEC' AND activo=1;
SELECT CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'NO_OK' END AS indicador_tec_net_activo FROM rg_indicadores WHERE codigo='TEC_NET' AND activo=1;
SELECT COUNT(*) AS registros_nacionales,CASE WHEN COUNT(*)=215 THEN 'OK' ELSE 'NO_OK' END AS estado FROM rg_datos_pais d JOIN rg_indicadores i ON i.id=d.indicador_id WHERE i.codigo='TEC_NET' AND d.activo=1;
SELECT CASE WHEN COUNT(*)=9 THEN 'OK' ELSE 'NO_OK' END AS datos_area_tec_esperados_9 FROM rg_datos_area d JOIN rg_indicadores i ON i.id=d.indicador_id WHERE i.codigo='TEC_NET' AND d.activo=1;
SELECT CASE WHEN COUNT(*)=243 THEN 'OK' ELSE 'NO_OK' END AS datos_area_totales_esperados_243 FROM rg_datos_area WHERE activo=1;
SELECT CASE WHEN COUNT(*)=234 THEN 'OK' ELSE 'NO_OK' END AS datos_area_anteriores_esperados_234 FROM rg_datos_area d JOIN rg_indicadores i ON i.id=d.indicador_id WHERE i.codigo<>'TEC_NET' AND d.activo=1;
SELECT p.codigo_iso3,d.valor FROM rg_datos_pais d JOIN rg_indicadores i ON i.id=d.indicador_id JOIN rg_paises p ON p.id=d.pais_id WHERE i.codigo='TEC_NET' AND d.activo=1 AND (d.valor<0 OR d.valor>100);
SELECT p.codigo_iso3,d.anio,d.valor FROM rg_datos_pais d JOIN rg_indicadores i ON i.id=d.indicador_id JOIN rg_paises p ON p.id=d.pais_id WHERE i.codigo='TEC_NET' AND d.activo=1 AND d.valor=0 AND p.codigo_iso3 NOT IN ('ASM','PRK','MNP','TCA');
SELECT p.codigo_iso3,d.anio,COUNT(*) AS repeticiones FROM rg_datos_pais d JOIN rg_indicadores i ON i.id=d.indicador_id JOIN rg_paises p ON p.id=d.pais_id WHERE i.codigo='TEC_NET' AND d.activo=1 GROUP BY p.codigo_iso3,d.anio HAVING COUNT(*)>1;
SELECT a.codigo,d.paises_totales,d.paises_con_dato,d.porcentaje_cobertura,d.anio_minimo,d.anio_maximo,d.valor FROM rg_datos_area d JOIN rg_indicadores i ON i.id=d.indicador_id JOIN rg_areas a ON a.id=d.area_id WHERE i.codigo='TEC_NET' AND d.activo=1 ORDER BY a.codigo;
SELECT a.codigo,d.valor AS valor_almacenado,ROUND(SUM(n.valor*p.valor)/SUM(p.valor),6) AS valor_recalculado,d.porcentaje_cobertura AS cobertura_almacenada,ROUND(100*SUM(p.valor)/(SELECT SUM(pt.valor) FROM rg_paises rpt JOIN rg_datos_pais pt ON pt.pais_id=rpt.id AND pt.indicador_id=ip.id AND pt.anio=2025 AND pt.activo=1 WHERE rpt.area_id=a.id),4) AS cobertura_recalculada,CASE WHEN ABS(d.valor-SUM(n.valor*p.valor)/SUM(p.valor))<0.000001 AND ABS(d.porcentaje_cobertura-100*SUM(p.valor)/(SELECT SUM(pt.valor) FROM rg_paises rpt JOIN rg_datos_pais pt ON pt.pais_id=rpt.id AND pt.indicador_id=ip.id AND pt.anio=2025 AND pt.activo=1 WHERE rpt.area_id=a.id))<0.0001 THEN 'OK' ELSE 'NO_OK' END AS estado FROM rg_datos_area d JOIN rg_indicadores i ON i.id=d.indicador_id JOIN rg_areas a ON a.id=d.area_id JOIN rg_paises rp ON rp.area_id=a.id JOIN rg_datos_pais n ON n.pais_id=rp.id AND n.indicador_id=i.id AND n.activo=1 JOIN rg_indicadores ip ON ip.codigo='POB_TOTAL' JOIN rg_datos_pais p ON p.pais_id=rp.id AND p.indicador_id=ip.id AND p.anio=2025 AND p.activo=1 WHERE i.codigo='TEC_NET' AND d.activo=1 GROUP BY a.id,a.codigo,d.valor,d.porcentaje_cobertura,ip.id ORDER BY a.codigo;
SELECT codigo,activo FROM rg_indicadores WHERE codigo IN ('TEC_ID','TEC_PESO');
